### ISSUE TITLE
Improving the program

### ISSUE THREAD

**Issue by KrishGarg** [NamVr/thrm#1]
I have some ideas to improve the software.

**Comment by KrishGarg** [comment]
As there is an error, whose score is more than 40% get less score displayed
so to fix that we can put like an if statement at the displaying lines of codes that where you might have written:
cout>>"HRM` Score:"+score, just before this statement if(score<40) {score=score+(score1/5)} or a statement like that(because i dont know c++ well pardon)

**Comment by NamVr** [comment]
Yes as per the recent changes in the company's policies in related to HRM, the score in the front end is projected 20% more than the actual score when the actual score is more than 40%

It seems a bit confusing. Can we have a detailed information on this issue?

**Comment by KrishGarg** [comment]
I want to say that for the employees not getting confused, we can program the software to show the correct risk ever after the error.

**Comment by NamVr** [comment]
Yes thanks for reporting and this will be taken as a new feature request in the new version of the project.
I will make the commit soon: V.0.5 With some bug fixes.

> I want to say that for the employees not getting confused, we can program the software to show the correct risk ever after the error.

Hm. I got you.

**Comment by KrishGarg** [comment]
Thanks for taking the suggestion! Have a good day.

**Comment by NamVr** [comment]
I think a simple block of quote will help this do the automation automatically.
We will just define the new block as comparison. I will do it soon thanks 👍

**Comment by NamVr** [comment]
# Issue Fixed - @KrishGarg 
Changelog is updated - 2 New features released.

New release and features are commited: 91d0fff0c8646ee89267a6c2ca050c6376dd3878

Issue Closed and Marked as resolved: Check out forums for latest updates.
https://support.teamelites.gq/d/7-thrm-risk-calculator-ai-software-is-out-finally

Regards,
@NamVr - Naman Vrati
